modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/xiewuzhiying/VS-Addition/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_addition"
version = "${version}"
displayName = "VS Addition"
authors = ["xiewuzhiying"]
description = '''
Some little addition for VS2 and other mods.
'''
logoFile = "icon.png"

[[dependencies.vs_addition]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_addition]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_addition]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "BOTH"
[dependencies.vs_addition.mc-publish]
ignore=false
modrinth="kotlin-for-forge"
curseforge="kotlin-for-forge"

[[dependencies.vs_addition]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"
[dependencies.vs_addition.mc-publish]
ignore=false
modrinth="architectury-api"
curseforge="architectury-api"

[[dependencies.vs_addition]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.1.3-beta.1,)"
ordering = "AFTER"
side = "BOTH"
[dependencies.vs_addition.mc-publish]
ignore=false
modrinth="valkyrien-skies"
curseforge="valkyrien-skies"

[[dependencies.vs_addition]]
modId = "create"
mandatory = false
versionRange = "[0.5.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_addition]]
modId = "createbigcannons"
mandatory = false
versionRange = "[0.5.2,)"
ordering = "AFTER"
side = "BOTH"
[dependencies.vs_addition.mc-publish]
ignore=false
modrinth="create-big-cannons"
curseforge="create-big-cannons"

[[dependencies.vs_addition]]
modId = "framedblocks"
mandatory = false
versionRange = "[5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_addition]]
modId = "computercraft"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_addition]]
modId = "vs_clockwork"
mandatory = false
versionRange = "[0.1,)"
ordering = "AFTER"
side = "BOTH"
[dependencies.vs_addition.mc-publish]
ignore=false
modrinth="create-clockwork"
curseforge="create-clockwork"

[mc-publish]
# This dependency declaration will be merged with everything written above.
# It's useful if you want to provide information about dependency types not supported by Forge.
# Or if you want to attach platform-specific aliases to one of the dependencies above.
dependencies=[
    "valkyrien-skies@>=2.1.3(required)",
    "kotlin-for-forge@>=4.10.0(required)",
    "architectury-api@>=9.0.0(embedded)",
    "create-clockwork@>=0.5.1(optional)",
    "create-big-cannons@>=5.5.0(optional)",
    "copycats@>=1.2.5(optional)"
]