name: Build 1.20.1
 
on:
  push:
    branches:
      - '1.20.1/**'
  pull_request:
    branches:
      - '1.20.1/**'
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  CURSEFORGE_ID: 1027757
  MODRINTH_ID: nR8D9Tc2  

permissions:
  contents: write

jobs:                                             
  build:                                          
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Download Modern Warfare
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./forge/jars/cbcmodernwarfare-0.0.5e+mc.1.20.1-forge.jar
          googleFileId: 1TJbrEHrX5RQcEkOHHKn6sU1rBWfltues

      - name: Download FTB Chunks
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./common/jars/ftb-chunks-fabric-2001.3.1.jar
          googleFileId: 1syotEGMA2svNL2vaXp35yF7fD9NyDmZp

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./common/build/libs/*
            ./fabric/build/libs/*
            ./forge/build/libs/*