#file: noinspection UndefinedParamsPresent,UndefinedAction
name: Publish 1.20.1 on GitHub, CurseForge & Modrinth
 
on: [ workflow_dispatch ]           

env:
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  CURSEFORGE_ID: 1027757
  MODRINTH_ID: nR8D9Tc2  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Download Modern Warfare
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./forge/jars/cbcmodernwarfare-0.0.5f+mc.1.20.1-forge.jar
          googleFileId: 15KCNyGuQKrEgxLQ0tSdnper99MO-CEyv

      - name: Download Create Big Cannons (Common)
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./common/jars/createbigcannons-5.6.0-dev-mc.1.20.1-fabric-build.87.jar
          googleFileId: 1e_HE8RAPTTIpMtmHp4n1VsoGumqyFlzG

      - name: Download Create Big Cannons (Fabric)
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./fabric/jars/createbigcannons-5.6.0-dev-mc.1.20.1-fabric-build.87.jar
          googleFileId: 1e_HE8RAPTTIpMtmHp4n1VsoGumqyFlzG

      - name: Download Create Big Cannons (Forge)
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./forge/jars/createbigcannons-5.6.0-dev-mc.1.20.1-forge-build.87.jar
          googleFileId: 1eaFIoPYUcroNHynGEgTK-gg5t1n_OHyl

      - name: Download Valkyrien Ship Schematics
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./common/jars/valkyrien-ship-schematics-fabric-1.0.jar
          googleFileId: 1hGQuv304eS5rO0VmR992T9WqmOTqHde2

      - name: Download Tallyho
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.GSA_CREDENTIALS }}
          actionType: download
          localPath: ./forge/jars/tallyho-3.0.8.jar
          googleFileId: 1B0JbYHXQOj_g666pOvs-FmDvK6hUd7LK

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./build/libs/merged/*
            ./common/build/libs/*
            ./fabric/build/libs/*
            ./forge/build/libs/*
            ./CHANGELOG.md

      - name: Read mod_version from gradle.properties
        id: read_mod_version
        run: |
          MOD_VERSION=$(grep 'mod_version' gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
          MINECRAFT_VERSION=$(grep 'minecraft_version' gradle.properties | cut -d'=' -f2)
          echo "MINECRAFT_VERSION=$MINECRAFT_VERSION" >> $GITHUB_ENV      

      - name: Publish (CurseForge/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: ${{env.CURSEFORGE_ID}}
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          github-tag: "v${{env.MOD_VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "[${{env.MINECRAFT_VERSION}} Multi-Loader] ${{env.MOD_VERSION}}"
          version: "${{env.MINECRAFT_VERSION}}-${{env.MOD_VERSION}}"
          version-type: beta
          changelog-file: CHANGELOG.md

          files: |
            ./build/libs/merged/*.jar

          loaders: |
            fabric
            forge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

      - name: Publish (Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{env.MODRINTH_ID}}
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          name: "[${{env.MINECRAFT_VERSION}} Multi-Loader] ${{env.MOD_VERSION}}"
          version: "${{env.MINECRAFT_VERSION}}-${{env.MOD_VERSION}}"
          version-type: beta
          changelog-file: CHANGELOG.md

          files: |
            ./build/libs/merged/*.jar

          loaders: |
            fabric
            forge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"